// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC3xZmOt1Mk4HBHp3kn64XLrR8tka9ezs',
    appId: '1:23707880762:web:32bbbf8ebe513bd54e1403',
    messagingSenderId: '23707880762',
    projectId: 'parttimecommunity-94108',
    authDomain: 'parttimecommunity-94108.firebaseapp.com',
    storageBucket: 'parttimecommunity-94108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCmh4P-wG6kyUj4kZaXhAvQywQL23oY7U',
    appId: '1:23707880762:android:f0f16ca28bc489a34e1403',
    messagingSenderId: '23707880762',
    projectId: 'parttimecommunity-94108',
    storageBucket: 'parttimecommunity-94108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUA7EgFaqoO7O8gtsGUOhC0ixV2pgnvUw',
    appId: '1:23707880762:ios:c559b50bd6eeabeb4e1403',
    messagingSenderId: '23707880762',
    projectId: 'parttimecommunity-94108',
    storageBucket: 'parttimecommunity-94108.appspot.com',
    iosClientId: '23707880762-dhbe734lcv2kn8j3084998uggoas6i2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
